apiVersion: batch/v1
kind: Job
metadata:
  name: ashs-dev-job-%ticket_id%
spec:
  template:
    metadata:
      name: ashs-dev-job
    spec:
      containers:
      - name: ashs-test-job
        image: %container%
        command: ["%command%"]
        args: [%args%]
        volumeMounts:
        - name: atlas
          mountPath: /app/atlas
        - name: auth
          mountPath: /root/.alfabis
          readOnly: true
        resources:
          requests:
            cpu: 15000m
      volumes:
      - name: atlas
        persistentVolumeClaim:
          claimName: pvc-ashs-atlases
          readOnly: true
      - name: auth
        secret:
          secretName: alfabis-cookie

      restartPolicy: Never
